version: '2.1'

services:
  app:
    build: .
    links:
      - db
    depends_on:
      db:
        condition: service_healthy
    environment:
      - hub=test
      - DATABASE_HOST=db
      - DATABASE_NAME=sinatra
      - DATABASE_USER=sinatra
      - DATABASE_PASSWORD=sinatra

  db:
    build: postgres
    environment:
      - POSTGRES_USER=sinatra
      - POSTGRES_PASSWORD=sinatra
    ports:
      - "5432:5432"
    healthcheck:
        interval: 30s
        timeout: 10s
        retries: 5
