require 'rake/testtask'
require './app'

DatabaseTasks.database_configuration = YAML.load(File.read(File.join(root, 'config/database.yml')))

Rake::TestTask.new do |t|
  t.libs << "test"
  t.test_files = FileList['test/*_test.rb']
  t.verbose = true
end

task default: :test
